"""add project_relation_user table

Revision ID: a2d3d19b62d2
Revises: f9fbf4aa6c3f
Create Date: 2025-05-15 10:50:51.791186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d3d19b62d2'
down_revision: Union[str, None] = 'f9fbf4aa6c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_relation_user',
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_permission', sa.Boolean(), nullable=False),
    sa.Column('write_permission', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index(op.f('ix_project_relation_user_project_id'), 'project_relation_user', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_relation_user_user_id'), 'project_relation_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_relation_user_user_id'), table_name='project_relation_user')
    op.drop_index(op.f('ix_project_relation_user_project_id'), table_name='project_relation_user')
    op.drop_table('project_relation_user')
    # ### end Alembic commands ###
