"""add api_token table

Revision ID: 0a4dea85a024
Revises: ec84950f2b01
Create Date: 2025-05-17 02:01:24.773764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4dea85a024'
down_revision: Union[str, None] = 'ec84950f2b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('api_token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_token_id')
    )
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_table('api_token')
    # ### end Alembic commands ###
