"""add assistant_chat_message table

Revision ID: 414674b157fa
Revises: 15d58d70675f
Create Date: 2025-05-17 10:11:16.320623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414674b157fa'
down_revision: Union[str, None] = '15d58d70675f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_chat_message',
    sa.Column('assistant_chat_message_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('assistant_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assistant_chat_message_id')
    )
    op.create_index(op.f('ix_assistant_chat_message_project_id'), 'assistant_chat_message', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_chat_message_project_id'), table_name='assistant_chat_message')
    op.drop_table('assistant_chat_message')
    # ### end Alembic commands ###
