"""add project table

Revision ID: f9fbf4aa6c3f
Revises: 542f6b63c95a
Create Date: 2025-05-15 00:32:05.251515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fbf4aa6c3f'
down_revision: Union[str, None] = '542f6b63c95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_project_owner_user_id'), 'project', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_owner_user_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
