"""change version tag to nullable

Revision ID: 7ffd5088a3cd
Revises: 0a4dea85a024
Create Date: 2025-05-17 07:58:07.847686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffd5088a3cd'
down_revision: Union[str, None] = '0a4dea85a024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_version_tag'), 'version', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_tag'), table_name='version')
    op.alter_column('version', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
