"""add tables_coordiante colors to version

Revision ID: 15d58d70675f
Revises: 7ffd5088a3cd
Create Date: 2025-05-17 10:10:34.011025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15d58d70675f'
down_revision: Union[str, None] = '7ffd5088a3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('tables_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('version', sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'colors')
    op.drop_column('version', 'tables_coordinates')
    # ### end Alembic commands ###
