import os

from dotenv import load_dotenv

from src.config.settings import PROJECT_DIR_PATH

load_dotenv()
CERTS_DIR_PATH = PROJECT_DIR_PATH / os.getenv("CERTS_DIR_NAME")
JWT_PRIVATE_KEY_NAME = os.getenv("JWT_PRIVATE_KEY_NAME")
JWT_PUBLIC_KEY_NAME = os.getenv("JWT_PUBLIC_KEY_NAME")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")

ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_MINUTES = int(os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES"))


if __name__ == "__main__":
    print(f"CERTS_DIR_PATH: {CERTS_DIR_PATH}")
    print(f"JWT_PRIVATE_KEY_NAME: {JWT_PRIVATE_KEY_NAME}")
    print(f"JWT_PUBLIC_KEY_NAME: {JWT_PUBLIC_KEY_NAME}")
    print(f"JWT_ALGORITHM: {JWT_ALGORITHM}")
    print(f"ACCESS_TOKEN_EXPIRE_MINUTES: {ACCESS_TOKEN_EXPIRE_MINUTES}")
    print(f"REFRESH_TOKEN_EXPIRE_MINUTES: {REFRESH_TOKEN_EXPIRE_MINUTES}")
